version: '3.7'
services:
  api:
    build: .
    image: cats-api-mongodb
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb-1
      MONGO_PORT: 27017
      MONGO_REPL_SET_NAME: ${MONGO_REPL_SET_NAME}

  mongodb-1:
    image: mongo:latest
    restart: always
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
      - ./mongodb-keyfile:/data/mongodb-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: --keyFile /data/mongodb-keyfile --replSet ${MONGO_REPL_SET_NAME}

  mongodb-2:
    image: mongo:latest
    restart: always
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
      - ./mongodb-keyfile:/data/mongodb-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: --keyFile /data/mongodb-keyfile --replSet ${MONGO_REPL_SET_NAME}

  mongodb-repl-set-init:
    image: mongo:latest
    volumes:
      - ./rs-init:/rs-init/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_REPL_SET_NAME: ${MONGO_REPL_SET_NAME}
      MONGO_REPL_SET_HOSTS: mongodb-1 mongodb-2
    entrypoint: sh /rs-init/rs-init.sh
